# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64" # Latest stable Debian release
  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
    v.memory = 2048
  end

  config.vm.define "yrignyS" do |server|
    server.vm.hostname = "yrignyS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.network "forwarded_port", guest: 80, host: 8080
    server.vm.provision "shell", path: "scripts/server.sh"
  end

end
